name: storage_chart
description:
  A simple Dart implementation of storage chart.

version: 0.5.0

homepage: https://github.com/dineshMadvise/storage_chart

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter